name: Request Salons API

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  
jobs:
  request-api:
    runs-on: ubuntu-latest

    steps:
      - name: Send GET request to API on Render
        run: |
          curl -X GET https://api-34m7.onrender.com
